name: Publish develop version
on:
  push:
    branches:
      - develop
jobs:
  Update-Develop-Version:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: netidee.cg.tuwien.ac.at
          username: netidee-server
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            bash /home/netidee-server/Server_Dev/deploy.sh
